version: "3.7"

services:
  nestjs-project:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DB_URL: mongodb://db/db_name
#      redis://<username>:<password>@<host>:<port>
      REDIS_URL: redis://default:password@redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      REDIS_USERNAME: default
#      postgres://username:password@host:port/database_name
      DATABASE_URL: postgres://username:password@postgres:5432/nestjs_app
      ENABLE_REDIS_CACHE_FOR_TYPEORM: true
      NODE_ENV: development
    volumes:
      - nestjs-project:/usr/src/appsrc
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
  postgres:
    ports:
      - 5433:5432
    build: postgres
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./tmp/pgdata/nestjs_app:/var/lib/postgresql/data
volumes: 
  nestjs-project:
