version: "3.7"

services:
  nestjs-project:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DB_URL: mongodb://db/db_name
#      redis://<username>:<password>@<host>:<port>
      REDIS_URL: redis://default:password@redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    volumes:
      - nestjs-project:/usr/src/appsrc
#  db:
#    image: mongo:4.0-xenial
#    ports:
#      - 27017:27017
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
volumes: 
  nestjs-project:
